buildscript {
    ext {
        kotlin_version = '2.3.20'
        agp_version = '9.1.1'
        compose_bom_version = '2026.04.01'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:$kotlin_version"
        classpath "androidx.benchmark:benchmark-baseline-profile-gradle-plugin:1.5.0-alpha07"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
