plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace "com.tranphuloi.neon"
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 20231111
        versionName "2023.11.11"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion "1.2.0-alpha02"
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildTypes.configureEach { crunchPngs = false }

    flavorDimensions.add("type")
    productFlavors {
        create("dev") {
            setDimension("type")
//            buildConfigField("String", "FLAVOR_buildEnv", "dev")

            resValue("string", "app_name", "Sky force 2024 DEV")

            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
            resValue("string", "BANNER", "")
            resValue("string", "INTER", "")

            resValue("string", "EnableAdInter", "false")
            resValue("string", "EnableAdBanner", "false")
        }
        create("production") {
            setDimension("type")
//            buildConfigField("String", "FLAVOR_buildEnv", "prod")

            resValue("string", "app_name", "Sky force 2024")

            resValue("string", "SDK_KEY", "e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt")
            resValue("string", "BANNER", "")
            resValue("string", "INTER", "")

            resValue("string", "EnableAdInter", "true")
            resValue("string", "EnableAdBanner", "true")
        }
    }
}

dependencies {
    /*Core*/
    implementation "androidx.core:core-ktx:1.7.0"
    implementation "com.google.android.material:material:1.4.0"
    implementation "androidx.activity:activity-compose:1.4.0"
    /*Compose*/
    implementation "androidx.compose.ui:ui:1.2.0-alpha02"
    implementation "androidx.compose.material:material:1.2.0-alpha02"
    implementation "androidx.compose.ui:ui-tooling-preview:1.2.0-alpha02"
//    debugImplementation "androidx.compose.ui:ui-tooling:1.2.0-alpha02"
    /*Accompanist*/
    implementation "com.google.accompanist:accompanist-systemuicontroller:0.20.3"
    /*Tests*/
//    testImplementation "junit:junit:4.13.2"
//    testImplementation "org.mockito:mockito-core:5.6.0"
//    testImplementation "org.mockito:mockito-inline:5.1.0"
    /*Audio player*/
    implementation "com.google.android.exoplayer:exoplayer:2.16.1"
    /*Image*/
    implementation "io.coil-kt:coil-compose:1.4.0"
    implementation "io.coil-kt:coil-gif:1.4.0"
    /*Navigation*/
    implementation "androidx.navigation:navigation-compose:2.4.0-rc01"
    debugImplementation("com.squareup.leakcanary:leakcanary-android:2.12")
}
